In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
file_path = r"/Users/pujithajujjarapu/Documents/680JobDatasSet.csv"
df = pd.read_csv(file_path, encoding="utf-8", engine="python", on_bad_lines="skip")
df.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713400e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712860e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713280e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712900e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713450e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [4]:
df.drop_duplicates()
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713400e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712860e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713280e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712900e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713450e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713570e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,NaN,1.713570e+12,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,NaN,1.713570e+12,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,1.713570e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713570e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [5]:
df.duplicated().sum()  # Check duplicate rows
df.drop_duplicates(inplace=True)  # Remove duplicate rows
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713400e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712860e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713280e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712900e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713450e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713570e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,NaN,1.713570e+12,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,NaN,1.713570e+12,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,1.713570e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713570e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [8]:
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,ComplexOnsiteApply,1.715450e+12,NaN,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,ComplexOnsiteApply,1.715490e+12,NaN,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,ComplexOnsiteApply,1.716040e+12,NaN,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,ComplexOnsiteApply,1.716160e+12,NaN,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,OffsiteApply,1.716160e+12,NaN,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,OffsiteApply,1.716160e+12,NaN,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,NaN,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,ComplexOnsiteApply,1.716160e+12,NaN,NaN,NaN,FULL_TIME,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,ComplexOnsiteApply,1.716160e+12,NaN,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [9]:
columns_to_modify = ['max_salary', 'views', 'med_salary', 'min_salary', 'applies', 'remote_allowed', 'normalized_salary', 'closed_time']
df[columns_to_modify] = df[columns_to_modify].fillna(df[columns_to_modify].mean())
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.000000,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.619876,...,ComplexOnsiteApply,1.715990e+12,1.712928e+12,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.00000,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.000000,HOURLY,"Fort Collins, CO",NaN,1.0,22015.619876,...,ComplexOnsiteApply,1.715450e+12,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.00000,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.000000,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.619876,...,ComplexOnsiteApply,1.715870e+12,1.712928e+12,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.00000,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.000000,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.619876,...,ComplexOnsiteApply,1.715490e+12,1.712928e+12,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.00000,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.000000,YEARLY,"Burlington, IA",NaN,3.0,22015.619876,...,ComplexOnsiteApply,1.716040e+12,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.00000,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.000000,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.619876,...,ComplexOnsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.00000,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.423461,NaN,United States,1124131.0,3.0,22015.619876,...,OffsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.03685,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.423461,NaN,"Spokane, WA",90552133.0,3.0,22015.619876,...,OffsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.03685,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.423461,NaN,"Texas, United States",2793699.0,4.0,22015.619876,...,ComplexOnsiteApply,1.716160e+12,1.712928e+12,NaN,NaN,FULL_TIME,NaN,NaN,205327.03685,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.000000,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.619876,...,ComplexOnsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.00000,92675.0

In [10]:
df = df.round({'max_salary': 1, 'med_salary': 1, 'normalized_salary': 1})
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,ComplexOnsiteApply,1.715990e+12,1.712928e+12,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,ComplexOnsiteApply,1.715450e+12,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,ComplexOnsiteApply,1.715870e+12,1.712928e+12,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,ComplexOnsiteApply,1.715490e+12,1.712928e+12,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,ComplexOnsiteApply,1.716040e+12,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,ComplexOnsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,NaN,United States,1124131.0,3.0,22015.6,...,OffsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,NaN,"Spokane, WA",90552133.0,3.0,22015.6,...,OffsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,NaN,"Texas, United States",2793699.0,4.0,22015.6,...,ComplexOnsiteApply,1.716160e+12,1.712928e+12,NaN,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,ComplexOnsiteApply,1.716160e+12,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [11]:
import datetime
# If the column is in datetime format, convert it to nanoseconds (if needed)

if pd.api.types.is_datetime64_any_dtype(df['expiry']):
    df['expiry'] = df['expiry'].astype('int64')  # Convert to integer type (nanoseconds)

# If the column is numeric, divide the nanoseconds by 1,000,000 to convert to milliseconds
df['expiry'] = df['expiry'] / 1_000_000  # Convert to milliseconds

# Now convert to datetime (milliseconds)
df['expiry'] = pd.to_datetime(df['expiry'], unit='ms')

df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.990,1.712928e+12,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.450,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.870,1.712928e+12,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.490,1.712928e+12,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.040,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,NaN,United States,1124131.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,NaN,"Spokane, WA",90552133.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,NaN,"Texas, United States",2793699.0,4.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,NaN,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [12]:
df.drop(columns=['closed_time'])
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.990,1.712928e+12,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.450,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.870,1.712928e+12,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.490,1.712928e+12,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.040,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,NaN,United States,1124131.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,NaN,"Spokane, WA",90552133.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,NaN,"Texas, United States",2793699.0,4.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,NaN,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [13]:
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.990,1.712928e+12,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.450,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.870,1.712928e+12,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.490,1.712928e+12,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.040,1.712928e+12,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,NaN,United States,1124131.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,NaN,"Spokane, WA",90552133.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,NaN,"Texas, United States",2793699.0,4.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,NaN,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [16]:
df.drop(columns=["closed_time"])

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_url,application_type,expiry,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.990,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.450,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.870,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.490,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.040,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,NaN,United States,1124131.0,3.0,22015.6,...,https://www.pinterestcareers.com/en/jobs/58824...,OffsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,NaN,"Spokane, WA",90552133.0,3.0,22015.6,...,https://epsoperations.bamboohr.com/careers/122...,OffsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,NaN,"Texas, United States",2793699.0,4.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.160,NaN,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [17]:
df.drop(columns=["closed_time"])

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_url,application_type,expiry,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.990,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.450,NaN,NaN,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.870,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:35.490,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.040,NaN,NaN,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,NaN,United States,1124131.0,3.0,22015.6,...,https://www.pinterestcareers.com/en/jobs/58824...,OffsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,NaN,"Spokane, WA",90552133.0,3.0,22015.6,...,https://epsoperations.bamboohr.com/careers/122...,OffsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,NaN,"Texas, United States",2793699.0,4.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.160,NaN,NaN,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,NaN,ComplexOnsiteApply,1970-01-01 00:28:36.160,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [22]:
columns_to_replace = ['pay_period', 'skills_desc']
df[columns_to_replace] = df[columns_to_replace].fillna("unknown")
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.990,1.712928e+12,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.450,1.712928e+12,NaN,unknown,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.870,1.712928e+12,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.490,1.712928e+12,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.040,1.712928e+12,NaN,unknown,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,unknown,United States,1124131.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,unknown,"Spokane, WA",90552133.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,unknown,"Texas, United States",2793699.0,4.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,NaN,unknown,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [31]:
df = df.round({'applie': 10})
df

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary,zip_code
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.990,1.712928e+12,NaN,Requirements: \n\nWe are seeking a College or ...,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.450,1.712928e+12,NaN,unknown,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.870,1.712928e+12,NaN,We are currently accepting resumes for FOH - A...,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:35.490,1.712928e+12,NaN,This position requires a baseline understandin...,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.040,1.712928e+12,NaN,unknown,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,91939.4,unknown,United States,1124131.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,NaN,NaN,205327.0,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,91939.4,unknown,"Spokane, WA",90552133.0,3.0,22015.6,...,OffsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,NaN,NaN,205327.0,99201.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,91939.4,unknown,"Texas, United States",2793699.0,4.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,NaN,unknown,FULL_TIME,NaN,NaN,205327.0,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k â€“ $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22015.6,...,ComplexOnsiteApply,1970-01-01 00:28:36.160,1.712928e+12,Mid-Senior level,unknown,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0

In [34]:
df['applies'] = df['applies'].round(0)

In [35]:
df.to_csv('cleaned_data.csv', index=False)